services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./frontend/build:/app/frontend/build
    environment:
      - DATABASE_URL=postgresql://dartos:dartos123@db:5432/dartos
      - XAI_API_KEY=${XAI_API_KEY:-}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_VERBOSE_LOGS=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dartos
      POSTGRES_USER: dartos
      POSTGRES_PASSWORD: dartos123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: